// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.media.autoplay.default", 1);
user_pref("app.normandy.user_id", "7cb8dd88-8ae0-4ee6-b29a-c8a4b66580b0");
user_pref("app.update.download.attempts", 0);
user_pref("app.update.elevate.attempts", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 1558497169);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1558496804);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1558497047);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1558496925);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1558496773);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.impressionId", "{82a0f8ba-8673-49d8-a185-8fa03d29a5b5}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1558411200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1558496845407");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1558498660407");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1558496783047");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1558500383047");
user_pref("browser.search.region", "VN");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 29619);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190507012018");
user_pref("browser.startup.homepage_override.mstone", "66.0.5");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1558496778077");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "66.0.5");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.push.userAgentID", "042c3806e5ab406c85f9b625d9928af9");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 30);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "66.0.5");
user_pref("extensions.lastPlatformVersion", "66.0.5");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"98169d00-1f05-4a0b-b380-7c47639f92b0\",\"screenshots@mozilla.org\":\"1ed542f0-1cbb-4452-84d2-947af99a314c\",\"webcompat-reporter@mozilla.org\":\"37cc0f50-72ca-45ec-a4a9-5c83ede1fa9c\",\"webcompat@mozilla.org\":\"c5b04a6e-af7a-49ef-b853-0dc7655b1569\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1558496864);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190507012018");
user_pref("media.gmp-manager.lastCheck", 1558496862);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.disable_button.openCertManager", false);
user_pref("security.sandbox.content.tempDirSuffix", "a4b74e4e-6f4b-4f9e-bd4b-6576c6d827cf");
user_pref("security.sandbox.plugin.tempDirSuffix", "34671741-d823-4e95-aa30-01a087309ffa");
user_pref("services.blocklist.addons.checked", 1558496998);
user_pref("services.blocklist.gfx.checked", 1558496998);
user_pref("services.blocklist.onecrl.checked", 1558496998);
user_pref("services.blocklist.pinning.checked", 1558496998);
user_pref("services.blocklist.plugins.checked", 1558496998);
user_pref("services.settings.clock_skew_seconds", -135);
user_pref("services.settings.last_etag", "\"1558483216037\"");
user_pref("services.settings.last_update_seconds", 1558496998);
user_pref("services.settings.main.language-dictionaries.last_check", 1558496998);
user_pref("services.settings.main.onboarding.last_check", 1558496998);
user_pref("services.settings.main.sites-classification.last_check", 1558496998);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1558496772);
user_pref("toolkit.telemetry.cachedClientID", "2405f0ca-f7f7-4833-b890-da89b1225f33");
user_pref("toolkit.telemetry.previousBuildID", "20190507012018");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
